# Generated by Django 3.2.6 on 2021-09-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash'), ('uttar predash', 'uttar predash')], max_length=100)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, upload_to='profiling')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
